[package]
name = "optd-adaptive-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datafusion-optd-cli = { path = "../datafusion-optd-cli" }
rand = "0.8"
datafusion = { version = "43.0.0", features = [
    "avro",
    "crypto_expressions",
    "encoding_expressions",
    "regex_expressions",
    "unicode_expressions",
    "compression",
] }
mimalloc = { version = "0.1", default-features = false }
tokio = { version = "1.24", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "sync",
    "parking_lot",
] }
optd-datafusion-bridge = { path = "../optd-datafusion-bridge" }
optd-datafusion-repr = { path = "../optd-datafusion-repr" }
console = "0.15"
